name: ❯ Python Pain001

on:
  pull_request:
    branches:
      - main
      - 'feat/*'
  push:
    branches:
      - main
      - 'feat/*'

jobs:
  # This job lints the Python code using Flake8
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ❯ Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: ❯ Install Flake8
        run: pip install flake8
      - name: ❯ Lint Python code using Flake8
        run: flake8 .

  # This job tests the Python code using pytest
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ❯ Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: ❯ Install pytest
        run: pip install pytest
      - name: ❯ Run pytest
        run: pytest

  # This job reads the version number from setup.cfg and sets it as an environment variable
  version:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: ❯ Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: ❯ Get version number from setup.cfg
        id: set-version
        run: |
          echo "::set-output name=version::$(python -c 'import configparser; cfg = configparser.ConfigParser(); cfg.read("setup.cfg"); print(cfg.get("metadata", "version"))')"

  # This job builds the distribution packages, and publishes them to PyPI
  build:
    needs: version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      VERSION: ${{ needs.version.outputs.version }}
      PKG_NAME: pain001
    steps:
      # Check out the repository code
      - uses: actions/checkout@v2
      - name: ❯ Set up Python 🐍
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: ❯ Install dependencies 📦
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      # Build distribution packages
      - name: ❯ Build distribution packages 🧰
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          python setup.py sdist bdist_wheel

      # Publish distribution packages to PyPI
      - name: ❯ Publish distribution packages to PyPI 🚀
        id: publish
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: ${{ env.TWINE_USERNAME }}
          password: ${{ env.TWINE_PASSWORD }}
          packages_dir: dist
          verify_metadata: true
          skip_existing: true

      # Generate the changelog based on git log and template file
      - name: Generate Changelog
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Append version information to CHANGELOG.md
          echo "## Release v${{ env.VERSION }} - $(date +'%Y-%m-%d')" >> ${{ github.workspace }}/CHANGELOG.md
          # Copy content of template file to CHANGELOG.md
          cat TEMPLATE.md >> ${{ github.workspace }}/CHANGELOG.md
          # Append git log to CHANGELOG.md
          echo "$(git log --pretty=format:'%s' --reverse $(git describe --tags --abbrev=0)..HEAD)" >> ${{ github.workspace }}/CHANGELOG.md
          # Append empty line to CHANGELOG.md
          echo "" >> ${{ github.workspace }}/CHANGELOG.md

      # Append the artifact links to the changelog
      - name: Append Artifact Links
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "" >> ${{ github.workspace }}/CHANGELOG.md
          echo "## Artifacts 🎁" >> ${{ github.workspace }}/CHANGELOG.md
          for filename in dist/*; do
            link="$(basename $filename)"
            echo "* [$link](${{ github.server_url }}/${{ github.repository }}/releases/download/v${{ env.VERSION }}/$link)" >> ${{ github.workspace }}/CHANGELOG.md
          done

      # Create a release
      - name: Create Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          draft: true
          prerelease: false

      # # Upload the distribution packages as release assets
      # - name: Upload Release Asset
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./dist/*
      #     asset_name: ${{ env.PKG_NAME }}-${{ env.VERSION }}-${{ matrix.python-version }}-${{ matrix.os }}.whl
      #     asset_content_type: application/zip
